"use strict";
exports.__esModule = true;
exports.companyRouter = void 0;
var express = require("express");
var companyController_1 = require("../../controllers/companyController");
var authorization_middleware_1 = require("../../middleware/authorization.middleware");
var createCompanyDTO_1 = require("../../dto/company/createCompanyDTO");
var dtoBodyChecker_1 = require("../../dto/util/dtoBodyChecker");
var createInternProjectDTO_1 = require("../../dto/company/createInternProjectDTO");
var companyRouter = express.Router();
exports.companyRouter = companyRouter;
companyRouter.post("/companies/", dtoBodyChecker_1.dtoValidationMiddleware(createCompanyDTO_1.CreateCompanyDTO), authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.createCompany);
companyRouter.put("/companies/user/:userId", dtoBodyChecker_1.dtoValidationMiddleware(createCompanyDTO_1.CreateCompanyDTO), authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.editCompany);
companyRouter["delete"]("/companies/user/:userId", authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.deleteCompany);
companyRouter.get("/companies/user/:userId", authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.getCompany);
companyRouter.get("/companies/", authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.getAllCompanies);
companyRouter.post("/companies/internship-project", dtoBodyChecker_1.dtoValidationMiddleware(createInternProjectDTO_1.CreateInternProjectDTO), authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.addInternShipJobToCompany);
companyRouter.get("/companies/internship-project/:companyId", authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.getInternShipProjectOfCompany);
companyRouter.get("/companies/fitting-internship-projects", authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.getFittingInternshipProjects);
companyRouter.get("/companies/company/:companyId", authorization_middleware_1.AuthorizationMiddleware.isAuthenticated, companyController_1.CompanyController.getCompanyById);
